### ISSUE TITLE
AttributeError: 'MSVCCompiler' object has no attribute 'compiler'

### ISSUE THREAD

**Issue by Erlinska** [roebel/py_find_1st#1]
Hello, I've tried to install this extension for quite a bit of time, but I keep falling into the same issue when running the commands in the cmd.

I've asked a lot of people about how to fix it, but I didn't manage to find an answer anywhere.

I'm getting the same error message, whether I run `python setup.py build_ext` or `python setup.py ìnstall` in the cmd:

D:\Chrome dl\py_find_1st-master>python setup.py build_ext
running build_ext
Traceback (most recent call last):
  File "setup.py", line 117, in <module>
    zip_safe = False,
  File "D:\Anaconda\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\Anaconda\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "D:\Anaconda\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Anaconda\lib\distutils\command\build_ext.py", line 338, in run
    self.build_extensions()
  File "setup.py", line 42, in build_extensions
    if compiler_is_clang(self.compiler.compiler):
AttributeError: 'MSVCCompiler' object has no attribute 'compiler'`

D:\Chrome dl\py_find_1st-master>python setup.py install
running install
running bdist_egg
running egg_info
creating py_find_1st.egg-info
writing py_find_1st.egg-info\PKG-INFO
writing dependency_links to py_find_1st.egg-info\dependency_links.txt
writing top-level names to py_find_1st.egg-info\top_level.txt
writing manifest file 'py_find_1st.egg-info\SOURCES.txt'
reading manifest file 'py_find_1st.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'py_find_1st.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib.win-amd64-3.5
creating build\lib.win-amd64-3.5\utils_find_1st
copying utils_find_1st\__init__.py -> build\lib.win-amd64-3.5\utils_find_1st
running build_ext
Traceback (most recent call last):
  File "setup.py", line 117, in <module>
    zip_safe = False,
  File "D:\Anaconda\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\Anaconda\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "D:\Anaconda\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Anaconda\lib\site-packages\setuptools-3.5.1-py3.5.egg\setuptools\command\install.py", line 65, in run
  File "D:\Anaconda\lib\site-packages\setuptools-3.5.1-py3.5.egg\setuptools\command\install.py", line 107, in do_egg_install
  File "D:\Anaconda\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Anaconda\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Anaconda\lib\site-packages\setuptools-3.5.1-py3.5.egg\setuptools\command\bdist_egg.py", line 157, in run
  File "D:\Anaconda\lib\site-packages\setuptools-3.5.1-py3.5.egg\setuptools\command\bdist_egg.py", line 143, in call_command
  File "D:\Anaconda\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Anaconda\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Anaconda\lib\site-packages\setuptools-3.5.1-py3.5.egg\setuptools\command\install_lib.py", line 8, in run
  File "D:\Anaconda\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "D:\Anaconda\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Anaconda\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Anaconda\lib\distutils\command\build_ext.py", line 338, in run
    self.build_extensions()
  File "setup.py", line 42, in build_extensions
    if compiler_is_clang(self.compiler.compiler):
AttributeError: 'MSVCCompiler' object has no attribute 'compiler'

Would you have any idea on how to fix it and manage to install the extension?

I've no knowledge of C++, and noone managed to find a solution, I have visual studio 2017 installed as well as its build tools extension.
I've verified that I installed everything necessary, yet no way to make the installation work.

The extension looks like it has very nice performances, and I hope to be able to use it in the future, any help would be gladly appreciated.

**Comment by roebel** [comment]
Hello,

sorry, I don't have a windows machine and therefore I cannot try with MSVC. I nevertheless think I understand the problem and have slightly changed setup.py such that it wont fail if a certain attribute of the compiler is not available.

Can you pull the new version and try with that? Please let me know if it works - then I would make a new release with the new setup and replicate the chage to other tools I have provided anwhich I never could test on windows.

Best
Axel

**Comment by Erlinska** [comment]
Hello,

Thank you very much for your answer, the installation is working perfectly fine and I can call the extension in python.

However, the test file doesn't work, and I get the following error:

--------------------------------

`runfile('D:/Chrome dl/py_find_1st-master (1)/py_find_1st-master/test/test_find_1st.py', wdir='D:/Chrome dl/py_find_1st-master (1)/py_find_1st-master/test')`
`Traceback (most recent call last):`

  `File "<ipython-input-17-3f26df3db751>", line 1, in <module>`
    `runfile('D:/Chrome dl/py_find_1st-master (1)/py_find_1st-master/test/test_find_1st.py', wdir='D:/Chrome dl/py_find_1st-master (1)/py_find_1st-master/test')`

  `File "D:\Anaconda\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)`

  `File "D:\Anaconda\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)`

  `File "D:/Chrome dl/py_find_1st-master (1)/py_find_1st-master/test/test_find_1st.py", line 9, in <module>`
   ` ind = utf1st.find_1st( arr, 10, utf1st.cmp_larger_eq)`

`ValueError: cc_find_1st::Input data type must be one of float64, float32, int64, int32, or bool.`

---------------------------------

I'm also getting an error when using a panda serie (which is expected , the data stocked is in int64 but the extension doesn't seem to handle pandas), but also when converting the pandas serie to a numpy array: 

-----------------------

  `File "D:/Programmes Python/Main_2.py", line 37, in <module>`
    `ind = utf1st.find_1st(high_array, limit, utf1st.cmp_larger_eq )`

`ValueError: cc_find_1st::Input data type must be one of float64, float32, int64, int32, or bool.`

`In[3]: type(high_array)`
`Out[3]: numpy.ndarray`
`In[4] high_array.dtype`
`Out[4]: dtype('int64')`

--------------------

Upon closer inspection, it looks like the problem is global to all array with int64 value:

`In [18]: a = np.array((1,2,3),dtype='int64')`

`In[19]: ind = utf1st.find_1st(a, limit, utf1st.cmp_larger_eq)`
`Traceback (most recent call last):`

  `File "<ipython-input-19-d141b4636568>", line 1, in <module>`
    `ind = utf1st.find_1st(a, limit, utf1st.cmp_larger_eq)`

`ValueError: cc_find_1st::Input data type must be one of float64, float32, int64, int32, or bool.`

-----------------------

I worked around the issue by specifying the dtype when converting my Series to numpy arrays, and it seems like I have much better performance using arrays with int32 datatype.

The extension works fine however for int32, float32, float64.

The increase in performance in very important (from more than 20s to less than 1s for the program I used it on), however, I don't get the same results as when using the equivalent numpy method, I'll investigate about it, the problem is probably in my program.

Anyway, thank you very much for your extension and your quick answer.

Nicolas

**Comment by roebel** [comment]
Ok, thanks for the ffedback!  I have looked into your int64 problem and I think that the macros I used for the test of the int size are using comiler specific definitions. I now changed to use macros with explicit bit size. This should resolve the problem with int64.

Let me know if it works now.
Best
Axel

**Comment by Erlinska** [comment]
Thank you very much for all the support, it's working perfectly now =).
