### ISSUE TITLE
py_find_1st for windows python 3.8 is still missing

### ISSUE THREAD

**Issue by williamvgam** [roebel/py_find_1st#12]
Hello, I am unfortunately not able to see what your problem could be. For me things seem to build fine under python 3.8 with pip21.1.3. I have precompiled anaconda packages available in the channel roebel [here](https://anaconda.org/roebel/py_find_1st). The package for python 3.8 was indeed missing but I just compiled and uploaded it. So you should be able to use conda to install it into your environment like this

```
 conda install -c roebel py_find_1st 
```

Let me know if this helps.

_Originally posted by @roebel in https://github.com/roebel/py_find_1st/issues/11#issuecomment-882083624_

**Comment by williamvgam** [comment]
![image](https://user-images.githubusercontent.com/101691704/162203822-b99b3e9a-55dc-4bbb-a34d-474013311266.png)

**Comment by roebel** [comment]
I am very sorry, but in my conda channel I support only linux and MacOS (besides for the moment M1). 
As I don't work under windows and don't have an Apple computer with the M1 processor I cannot provide any 
conda packages for those.

If you are interested to build such conda packages yourself you find the scripts for MacOS and Linux in the py_find_1st subdirectory of [this](https://github.com/roebel/conda_packages) repos.

**Comment by williamvgam** [comment]
Many thanks for your quick reply!  I'll try it then.

**Comment by williamvgam** [comment]
> I am very sorry, but in my conda channel I support only linux and MacOS (besides for the moment M1). As I don't work under windows and don't have an Apple computer with the M1 processor I cannot provide any conda packages for those.
> 
> If you are interested to build such conda packages yourself you find the scripts for MacOS and Linux in the py_find_1st subdirectory of [this](https://github.com/roebel/conda_packages) repos.

@roebel  Hello Roebel, 
I'm sorry to bother you again .I'am still with this problem that "py_find_1st for windows python 3.8 is still missing]". I am trying to build the package but not capable with that!

It will be grateful if  you could  kindly help !
Thanks!

**Comment by roebel** [comment]
The problem for me is that I don't work with windows computers and don't know how to setup a compiler for python packages under windows. That said if I can help I'd be happy to do this. So what kind of problem do you encounter?

**Comment by williamvgam** [comment]
@roebel I got it,  thank you all the same!
