### ISSUE TITLE
libstdc++ is deprecated on macOS

### ISSUE THREAD

**Issue by dericdesta** [roebel/py_find_1st#3]
libstdc++ was removed in macOS (XCode Command Line Tools v10), but py_find_1st is installable by changing to suggested libc++:

```python
            if compiler_is_clang(self.compiler.compiler):
                for e in self.extensions:
                    e.extra_compile_args.append('-stdlib=libc++')
                    e.extra_compile_args.append('-Wno-unused-function')
                for e in self.extensions:
                    e.extra_link_args.append('-stdlib=libc++')
```

**Comment by roebel** [comment]
Yes, in fact I don't need any specific stdlib here, so propose to remove the setting alltogether - it should work fine with the default.
I did that in version 1.1.3 - pease try and let me know if this works fine for you.

**Comment by dericdesta** [comment]
Unfortunately, version 1.1.3 does not fix this issue, at least on my mac. Have to pass `-stdlib=libc++` explicitly.

**Comment by roebel** [comment]
I am not sure why this is so, but I would think this then more a problem on your end. The default setup of the python distutils should work, if it doesn't then I don't see what I can do about that.

You can see some ways to change the default compiler flags that are used in your system (and that as far as I understand are the once that are used for compiling your python interpreter) here 
https://stackoverflow.com/questions/16077481/distutils-compiler-options-configuration.
