### ISSUE TITLE
Installation stalls

### ISSUE THREAD

**Issue by gitgitgat-zz** [roebel/py_find_1st#6]
Running ubuntu 18:

'pip install py-find-1st' just stalls, nothing happens.

**Comment by roebel** [comment]
I am running ubuntu18.04 myself, I just tried    `pip install py-find-1st`
it runs fine here. Please try `pip install --verbose py-find-1st` and see what it returns.

**Comment by gitgitgat-zz** [comment]
okay, `pip install py-find-1st` worked fine now, it was a problem with the conda and venv environments being mixed up.

**Comment by roebel** [comment]
Good, thanks for letting me know.
