### ISSUE TITLE
i can't install on windows 10 

### ISSUE THREAD

**Issue by tarantula3535** [roebel/py_find_1st#7]
![image](https://user-images.githubusercontent.com/63812786/100638550-36cb8680-3345-11eb-8894-e2f615f6182f.png)
i have an error like that
python 3.8.6.
windows 10 
How can i solve this error?

**Comment by roebel** [comment]
I am sorry I don't have windows and so I don't see anything I could do to help you here.

**Comment by KeM1aL** [comment]
The problem comes from numpy version. 
There is a bug on windows using numpy 1.19.4. I can't find a way to force using numpy 1.19.3 ...

**Comment by roebel** [comment]
Please see my explanations in  issue #8 for bypassing the automatic dependency handling.

**Comment by tarantula3535** [comment]
> The problem comes from numpy version.
> There is a bug on windows using numpy 1.19.4. I can't find a way to force using numpy 1.19.3 ...

yes first using nump 1.19.3 then download the package manually unpack and build manually as is explained in the file INSTALL.txt. i solve this using this steps...
